In [2]:
import numpy as np
from sklearn import preprocessing

In [3]:
input_data = np.array([
    [5.1, -2.9, 3.3],
    [-1.2, 7.8, -6.1],
    [3.9, 0.4, 2.1],
    [7.3, -9.9, -4.5]
])

In [4]:
binarized_data = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print(f"\nBinarized data:\n{binarized_data}")


Binarized data:
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
